[package]
name = "onix_os"
version = "0.1.0"
edition = "2018"
authors = ["Karan Singh <karan87564@gmail.com"]

[dependencies]
bootloader = "0.9"
volatile = "0.2.6"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


[[bin]]
name="onix_os"
test = false
doctest = false
bench = false